/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:966692:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield1:966692:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:247680:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  int inizio;
  int maxtempo=100;
  giocatore= new Client(this,textfield1.getText(),PORTA);
  giocatore.write("connetto");
  String letto;
  inizio=millis();
  while((millis()-inizio)<=maxtempo){
    letto=giocatore.readString();
    if(letto!=null && letto.equals("H")){
      textfield1.setVisible(false);
      button1.setVisible(false);
      statoRete=0;
    }
  }
  textfield1.setText("");
} //_CODE_:button1:247680:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  textfield1 = new GTextField(this, 300, 250, 100, 30, G4P.SCROLLBARS_NONE);
  textfield1.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
  button1 = new GButton(this, 407, 250, 87, 30);
  button1.setText("Connetti");
  button1.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  button1.addEventHandler(this, "button1_click1");
}

// Variable declarations 
// autogenerated do not edit
GTextField textfield1; 
GButton button1; 
